image:
  repository: ghcr.io/linuxserver/qbittorrent

service:
  containerPort: 80

config:
  mountPath: /config

persistence:
  enabled: false

serviceAccount:
  create: false

env:
  - name: PUID
    value: "1000"
  - name: PGID
    value: "1000"