image:
  repository: lscr.io/linuxserver/prowlarr

service:
  containerPort: 9696

config:
  mountPath: /config

persistence:
  enabled: true

serviceAccount:
  create: false

env:
  - name: PUID
    value: "1000"
  - name: GUID
    value: "1000"