image:
  repository: lscr.io/linuxserver/radarr

service:
  containerPort: 7878

config:
  mountPath: /config

persistence:
  enabled: false

serviceAccount:
  create: false

env:
  - name: PUID
    value: "1000"
  - name: PGID
    value: "1000"